### ISSUE TITLE
But how to get all data as result? Search what char, would get me all data?

### ISSUE THREAD

**Issue by hoogw** [olivernn/lunr.js#441] opened 2020-01-17 22:39 UTC
But how to get all data as result? Search what char, would get me all data?

I need this for pagination:

For page 1: you search something to get all dataset as result. Now you use for loop through, only get 1 to 10 records,then break for loop.

For page 2: you perform same search again, you should get the same result set as last time, but you this time you use for loop, from 11 to 20. Because offset is 10(you skip first 10).

and so on

For page x: you perform same search again, you should get the same result set as last time, but this time you use for loop, from (x * 10+1) to ((x * 10+1) +10). Because offset is x * 10 (you skip first x * 10).

**Comment by hoogw** [comment] 2020-01-17 23:40
I test the answer is 
         
                 `idx.search('')  
                    
                     or 

                     idx.search(' ')

                     or 

                      idx.search('  ')
`

search empty, or space, or 2 space, you will get all dataset as result.

**Comment by olivernn** [comment] 2020-01-22 19:38
I'm going to close this as a duplicate of #440

**Closed by olivernn** 2020-01-22 19:38 UTC
