### ISSUE TITLE
Empty index with v2.0.0-alpha5

### ISSUE THREAD

**Issue by iDams** [olivernn/lunr.js#252] opened 2017-03-30 09:13 UTC
Hey,

Let me know if it is too soon to try to use v2 but I'm interested in the query by field.
Otherwise I'll use the trick explained in #125 

```
var idx = lunr(function() {

  this.ref("id");

  this.field("name", { boost: 100 });
  
  fs.readFile("./src/export.json", (err, data) => {
    if (err) throw err;

    var raw = JSON.parse(data);
    var items = raw.items;

    items.map(item => {
      this.add(item);
      console.log(`Index ${item.id} added`);
    });
  });
});

fs.writeFile("./public/index.json", JSON.stringify(idx), function(err) {
  if (err) throw err;
  console.log("Index file has been created successfully!");
});
```

When I do this, index file is created but it is empty
```
{"version":"2.0.0-alpha.5","averageDocumentLength":null,"b":0.75,"k1":1.2,"fields":["name"],"documentVectors":[],"invertedIndex":[],"pipeline":["stemmer"]}
```

Am I doing something wrong to create the index?
This code was working with v1.

Thanks for your help!

**Comment by olivernn** [comment] 2017-03-30 18:20
Not too early to try out v2, in fact, the more people giving me feedback the better!

At first I thought that the issue was that the documents were not being added within the closure passed to the `lunr` function but it looks like you've done that. What you have looks very similar to what I have in the [demo site](https://github.com/olivernn/moonwalkers/blob/master/build-index#L18-L38). I even tried locally changing the forEach to use a fat arrow function and still got the correct results.

You could try logging the documentCount after adding all the documents:

```javascript
console.log(this.documentCount)
```

I've started putting together some documentation, specifically a [guide](https://github.com/olivernn/lunr-site/blob/master/source/guides/upgrading.html.md) for upgrading that might come in useful.

**Comment by olivernn** [comment] 2017-03-30 18:27
Ah, I *think* the issue is because you are using the async fs read/write functions. If you can, try switching to the sync versions, you should get the correct results.

**Comment by olivernn** [comment] 2017-03-30 18:36
I re-wrote your example taking into account the async fs operations and got a populated index:

```javascript
var lunr = require('lunr'),
    fs = require('fs')

fs.readFile('./docs/corpus.json', (err, data) => {
  var idx = lunr(builder => {
    builder.ref('id')
    builder.field('name')

    JSON.parse(data).forEach((doc) =>
      builder.add(doc)
    })
  })

  fs.writeFile('example.json', JSON.stringify(idx), (err) => {
    if (err) throw err
    console.log("done")
  })
})
```

Async programming is annoying!

**Comment by iDams** [comment] 2017-03-31 05:42
It is annoying!
It works thanks!

Also just saw your PR in https://github.com/MihaiValentin/lunr-languages to update to v2
I will try it.
I also have to figure out how stemmer/stop words work because, I still get weird results. Some words are cut before the end, so when the user type the exact word it does not match.

Thanks again for your help!
Great work

**Comment by olivernn** [comment] 2017-03-31 06:09
No problem, do you have anymore details on the weird results?

Regarding the lune-languages PR, take a look and try it out, if you have any feedback comment on that PR, else, add a plus one on it to help get it merged.

**Comment by iDams** [comment] 2017-03-31 07:42
Yep, I have two examples:
1- I have the word "type", it is indexed as "typ". When I search for "typ" I get the good result but with "type", I don't get any results.

2- I have two different words in the same result: "cons" and "connard". They are indexed as "con" and "connard" respectively. When I search for "con", I get the result but only "con" is matching not "connard". I get no results when I type "conn", "conna", "connar". Then I finally get a result when I type "connard".

Let me know if you have some input on this.
I will take a look at your PR in lunr-languages.

Thanks again

**Comment by olivernn** [comment] 2017-03-31 09:37
Thanks for the examples, could you provide an example JSON document, one for each of the issues you saw, then I can try and re-create the issues you are seeing.

**Comment by iDams** [comment] 2017-03-31 09:54
Sure.

Here is the data: https://cc-reborn.firebaseapp.com/data.json
Here is the index created with the v2: https://cc-reborn.firebaseapp.com/build-index.json

**Comment by olivernn** [comment] 2017-04-01 09:47
I used your [data](https://cc-reborn.firebaseapp.com/data.json) to build this [index](https://gist.github.com/olivernn/8003630469ea7bc465383ffd4ef16a46), which you can load using `lunr.Index.load(JSON.parse(...))`

I was unable to re-create the first problem, I can search for "type" and get back results. That said I see in the [index](https://cc-reborn.firebaseapp.com/build-index.json) you built, it is indexed as "typ", were you using the french language extension?

The other two issues are due to a change in the way searches are handled in 2.x. Previously an automatic wildcard was inserted at the end of each search term, this is no longer the case and for these kinds of searches you must include the wildcard yourself. For example, if you search for "con*" and "jac*" you should see the results that you expect. This is not mentioned in the upgrading guide I linked you too, it should be. For more on searching look at the [searching guide](https://github.com/olivernn/lunr-site/blob/master/source/guides/searching.html.md).

**Comment by iDams** [comment] 2017-04-01 10:11
> were you using the french language extension?

Yes, I'm sorry I forgot to mention it :/

Ah thanks, the wildcard should fix all 3 "issues" then.

I just saw in the searching guide you linked that you can search by fields like this `idx.search('title:foo')`
I have a performance question.
I have multiple tabs, one tab correspond to a field.
 Do you think it is better to search for every fields at once and then filter results by tab.
Or search by field when user switch tabs?
I don't know how much cost a search operation.
It seems really fast right now but I don't have a lot of indexes. 

Thanks for all your help!

**Comment by olivernn** [comment] 2017-04-01 15:54
Do you mean do a search for a term in all fields but only show results for one field at a time?

You probably _could_ do this, though I'd say its simpler to just to the search for the one field you need when you need it. If you do see performance issues with larger amounts of data then open an issue and we can investigate.

**Closed by olivernn** 2017-04-01 15:54 UTC
