### ISSUE TITLE
Sorting

### ISSUE THREAD

**Issue by jbavington713** [olivernn/lunr.js#67] opened 2014-01-24 11:52 UTC
Hi!

I'm still learning so be gentle...

Is there a way to re-order or sort the results after a search?

I have a working implementation with some numeric data and I want to bring the largest values for a specific term to the top.

Any help would be really appreciated.

Thanks

**Comment by olivernn** [comment] 2016-01-19 16:54
Closing this now, feel free to re-open if you have any other questions.

**Closed by olivernn** 2016-01-19 16:54 UTC

**Comment by nnmrts** [comment] 2017-02-27 10:29
I don't want to reopen here, but how could I sort the results by a given factor in an index entry. For example popularity or so.

**Comment by olivernn** [comment] 2017-02-27 17:49
Well, the results are an array of score and document ref. So you can re-sort it however you want, including looking up the existing document by its ref from wherever you have it in memory. As a reminder, lunr does _not_ keep a copy of the indexed documents itself.

**Comment by nnmrts** [comment] 2017-03-02 05:21
@olivernn Okay, thanks! Just out of curiosity, can I set two or more refs in one lunr index? If not, wouldn't that be a cool feature? I mean, I just imagined setting two different refs, for example one with the filename in it for alphabetic sorting and one with a popularity number. I know, I just could load up the documents or make a store of these values by my own to access this data, but this would be an additional step and seems performance-heavy, especially in my case, when trying to handle 3 million different and changing documents.

By the way, thank you for this library! I really like it! 👍

**Comment by olivernn** [comment] 2017-03-08 19:08
The problem is that Lunr is not intended to be the store of all your documents. How this data is stored would be very application specific, and trying to provide a reasonable interface would add quite a bit of complexity. The simplest thing for Lunr is to provide you with a key that you can use to lookup documents in whatever store you keep them in, be that locally in memory, or remotely via xhr.

I'm glad that Lunr is working well for you, especially with 3 million documents!
