### ISSUE TITLE
Partial word matching

### ISSUE THREAD

**Issue by dannydan412** [olivernn/lunr.js#68] opened 2014-01-29 18:34 UTC
Hi Oliver,

Do you know if it's possible to add partial word matching support to lunr?
Currently it seems that it adds a wildcard to the end of each token but not to the beginning. So for example, if I search for "create" and the document has the word "recreate" it wouldn't find it. I know stemming may be a solution to this, but I prefer not to use it. Also, on a similar subject, how difficult would it be to add fuzzy matching (e.g. if I made a typo and searched for "recreete" instead of "recreate"). Can you give me some pointers as to where in the code I should be looking to address these?

Thank you!!

**Comment by guirip** [comment] 2017-02-13 10:51
Hello all

Is there any new information about how to perform partial word matching?

e.g. My need is the following :
- an entry named: 'THAT XYZ COMPANY'
- must be retrieved when the user types: 'MPAN'
- must work with french words too

If there is no simple way to do this with `lunr.js`, is there another library you could advise me ?

Cheers

**Comment by olivernn** [comment] 2017-02-13 20:18
This is available in the upcoming [2.x](https://github.com/olivernn/lunr.js/tree/2.x) release of lunr.

You can try this out now on the [demo](https://olivernn.github.io/moonwalkers/) I put up, for example try a search with "\*tronau\*" and you should see documents matching "astronauts".

There is a fairly stable alpha release that you can try out available on npm, add this to your dependencies:

```javascript
{
  "dependencies": {
    "lunr": "alpha"
  }
}
```

As for language support, this will happen, but the existing [lunr-languages](https://github.com/MihaiValentin/lunr-languages) project has not yet been updated to support a change in interface required for the 2.x branch. Support will be available by the time 2.x is live.

There are small changes in the interface to use 2.x, hopefully the [example app](https://github.com/olivernn/moonwalkers/blob/master/build-index#L18-L38) makes this clear.

There will be a 2.x release soon, but any feedback on the alpha will be really useful, so if you have a chance to try this out I'd be super grateful.

**Comment by guirip** [comment] 2017-02-15 15:12
Great news ! :-)

I've read your example and had a few tries, but I can't get any single result, I must be missing something. Here is a very basic jsfiddle where an `alert` displays the results count :
[https://jsfiddle.net/of54k0uk/3/](url)

**Comment by olivernn** [comment] 2017-02-15 17:55
I've updated your example, there are no automatic wildcards like in the current version of lunr, so you have to search for "fast*".

That said, there is something odd going on because it doesn't seem to be handling the all caps query very well, I'll take a look.

**Comment by olivernn** [comment] 2017-02-15 19:39
Oops, forgot the link to the [fiddle](https://jsfiddle.net/of54k0uk/4/)

**Comment by olivernn** [comment] 2017-02-15 19:59
I've just pushed alpha.4 now that has a fix for the issue around upper case queries, I've also updated the [fiddle](https://jsfiddle.net/of54k0uk/5/) again to make use of the latest version.

Thanks for taking the time to test the alpha, this kind of testing is really useful. If you find any other problems while testing feel free to open an issue.

**Comment by guirip** [comment] 2017-02-16 09:45
Thanks !! It's good to see the results coming out !

As I trigger search from a generic field filled by the user, I automatically add starting and ending wildcards (e.g. If user types 'abc', then I trigger a lunr search for '*abc*'.). This is what I notice:

Let's say I have an entry named 'ABC PETSCHE COMPANY'.
-  [x] If user types 'OMPAN', the entry is returned as expected.

-  [x] If user types 'COMPAN', the entry is returned as expected.

-  [ ] If user types 'OMPANY', the entry is not returned... [jsfiddle/8](https://jsfiddle.net/of54k0uk/8/). The last wildcard seems to mean 'any', but the starting wildcard works as '0 or any' which is good to me. Search for '*abc*' and you get the result.

- [ ] If user types ' COMP' (notice the starting space), an exception occurs here [https://github.com/olivernn/lunr.js/blob/v2.0.0-alpha.4/lunr.js#L1741](https://github.com/olivernn/lunr.js/blob/v2.0.0-alpha.4/lunr.js#L1741): 
```
TypeError: Cannot read property '_index' of undefined
    at lunr.Index.query (webpack:///./~/lunr/lunr.js?:1741:32)
    at lunr.Index.search (webpack:///./~/lunr/lunr.js?:1647:15)
```
This is what happens on my app. Here is [jsfiddle/9](https://jsfiddle.net/of54k0uk/9/), simply add a starting space and you'll get ```uncaught exception: duplicate index```, which seems to be kind of a different error from the one I get on my project.

This is what I can tell you for now ;-) Will notice you if I find anything else.
Cheers

**Comment by guirip** [comment] 2017-02-16 10:49
Ok, I reproduced the last issue I noticed. It just needed more data. Here is the [jsfiddle](https://jsfiddle.net/of54k0uk/10/).

- [x] Search for 'CAM' : success
- [ ]  Search for 'COM': failure, you get an exception at [https://github.com/olivernn/lunr.js/blob/v2.0.0-alpha.4/lunr.js#L1741](https://github.com/olivernn/lunr.js/blob/v2.0.0-alpha.4/lunr.js#L1741): 
```
TypeError: Cannot read property '_index' of undefined
    at lunr.Index.query (webpack:///./~/lunr/lunr.js?:1741:32)
    at lunr.Index.search (webpack:///./~/lunr/lunr.js?:1647:15)
```

**Comment by olivernn** [comment] 2017-02-16 17:23
Okay, that exception you are getting is bug in the library. It seems that somehow the term '*com*' is expanding to a word that does not exist in the index, this shouldn't happen. Terms with wildcards are expanded using words that do exist in the index (using the TokenStore object). How this object is built is quite complicated, and I'm going to have to try and create a reduced test case to be able to step through the code to understand why this is happening.

There is a workaround that can be added to the library, but I'd rather fix the underlying bug.

**Comment by olivernn** [comment] 2017-02-16 20:37
Ok, I just pushed a change which fixes this issue, I've also updated the [fiddle](https://jsfiddle.net/of54k0uk/11/). Thanks for reporting this. If you find anything else while testing then please open an issue. Its probably best to open a new issue, just so things are easier to track.

**Comment by guirip** [comment] 2017-02-20 10:20
*facepalm*, you're totally right, I don't why I have not created new issues.

Thanks for the fix ! will let you know if I find anything suspicious.

**Comment by olivernn** [comment] 2017-02-20 10:55
Ha, no problem, I'm just thankful for getting some great feedback and some alpha testing!

**Comment by olivernn** [comment] 2017-05-20 12:31
Resolving this now as I think the original, and follow up issues, have been resolved.

**Closed by olivernn** 2017-05-20 12:31 UTC

**Comment by Beramos** [comment] 2019-11-20 19:39
> _facepalm_, you're totally right, I don't know why I have not created new issues.
> 
> Thanks for the fix ! will let you know if I find anything suspicious.

Love the '*' + query +'*' hack
