### ISSUE TITLE
Capital words should Not be stemmed

### ISSUE THREAD

**Issue by erichiller** [olivernn/lunr.js#250] opened 2017-03-15 00:31 UTC
Ran into this one today,

Using the default pipeline, and thus the stemmer.
The stemmer chops off `-er`
Which is often appropriate, but not in Proper nouns. It would not be possible to maintain a complete list of proper nouns, but Capitalization is a good sign. Thoughts?
Last names ending in `-er` are escaping indexing.

**Comment by olivernn** [comment] 2017-03-15 17:34
By the time tokens arrive at the stemmer they have already been converted to lower case, so relying on capitalisation won't work.

That said, what is the issue here? Even if proper nouns _are_ stemmed, they should still be searchable. Do you have an example of where this is causing unexpected results when searching?

**Comment by yashgorana** [comment] 2017-03-16 07:57
Try adding `Tom Clancy's Rainbow Six Siege`
Works fine when querying for `tom`, `rainbow`, `six`, `siege` but returns no documents when we query for `clancy` or `tom clancy`.

When adding document, the pipeline processes as follows:
1. trimmer output -> `clancy's`
2. stopword removal output -> `clancy's` 
3. stemmer output -> `clancy'` (notice the inverted comma, possible bug?)

The term `clancy'` is then added to the TokenStore.

Now here is the part which causes unexpected results - When querying for `clancy`, the pipeline stems the word to `clanci`. This token is not available in the TokenStore, thus index search yields no results.
Also, when querying for `clancy's`, the index returns correct result because the stemmed token `clancy'` is present in the TokenStore.

**Comment by olivernn** [comment] 2017-03-16 19:28
Thanks for the reproduction, so the issue isn't so much the name, rather the punctuation that is being correctly trimmed?

Looking at the [tests](https://github.com/olivernn/lunr.js/blob/master/test/trimmer_test.js#L17) for the [trimmer](https://github.com/olivernn/lunr.js/blob/master/lib/trimmer.js) there is a specific test for _not_ handling this case. I don't know why this is, especially since it seems to cause problems when stemming. I'll look at trying to handle this case in the trimmer, as well as trying to remember _why_ this case is explicitly ignored.

**Comment by olivernn** [comment] 2017-03-16 19:50
As a workaround you can add a pipeline function to manually trim the apostrophe s from tokens, example [fiddle](http://jsfiddle.net/zg8eng3f/3/).

**Comment by olivernn** [comment] 2017-03-23 17:30
This is actually the same issue as described in #192. I encourage you to take a look through that issue and some of the discussion. It looks like I also specifically put together a small [plugin](https://gist.github.com/olivernn/7cd496f8654a0246c53c) for working around more of these [contractions](https://en.wikipedia.org/wiki/Contraction_(grammar)#English).

I'm going to close this issue in favour of #192. @erichiller Please re-open if your issue wasn't related to the use of apostrophes.

**Closed by olivernn** 2017-03-23 17:30 UTC
