### ISSUE TITLE
Unexpected behavior: numeric type refs get converted to strings once indexed.

### ISSUE THREAD

**Issue by sherbondy** [olivernn/lunr.js#326] opened 2018-01-18 23:50 UTC
Hi there!

Love the library, but ran into unexpected behavior recently when updating from the ancient 0.6 release to the new-and-shiny 2.1.5 release.

Notably, I was formerly passing in an id ref with a numeric value, and the older lunr.js codebase seemingly left my ref types alone.

Now, refs get coerced into strings once more!

Is this the desired / expected behavior of the library?
Is there a new technical/performance reason behind this change related to the introduction of the immutable index?

The Changelog indicates this is a regression from 0.6 where the problem was originally resolved: #117

Simple repro notebook on RunKit just for fun:
https://runkit.com/sherbondy/lunr-js-2-1-5-converts-ref-values-to-strings-unexpectedly

Thanks for making lunr!

**Comment by olivernn** [comment] 2018-04-30 18:00
I remember the issue you are talking about. I honestly can't remember the reasons _why_ this change in  2.x of Lunr, but looking at the [docs](https://lunrjs.com/docs/lunr.Builder.html#ref) it seems I _did_ call it out specifically!

I'm not against 'fixing' this regression and would welcome pull requests with such changes ;)

I'll take a look into it myself also, but its not super high on my list of things to work on in Lunr.

**Comment by olivernn** [comment] 2018-06-06 19:52
Going to close this now as this _is_ documented behaviour (though it _has_ changed during the major version bump from 0/1 to 2).

As mentioned before, I am open to pull requests that support numeric refs, but I don't see myself getting to this anytime soon.

**Closed by olivernn** 2018-06-06 19:52 UTC
