### ISSUE TITLE
strange behavior 

### ISSUE THREAD

**Issue by sagiBarkol** [olivernn/lunr.js#210] opened 2016-03-10 14:18 UTC
i indexed a list of objects by there name property, the search look good but one issue came up.
im searching a term on each keystroke when im starting to type 'delegate' i get good result till 'deleg' and no result till i finish the word. (screenshot attached)

![delegate_search_result](https://cloud.githubusercontent.com/assets/17765637/13671778/97a97dc0-e6da-11e5-92b7-2522ef55b9a6.png)

**Comment by chrisdl** [comment] 2016-05-23 14:49
I'm having the same issue with the word Invisible.

It catches it until Invis but then the "i" causes it to fail until I complete the word.

**Comment by chrisdl** [comment] 2016-05-23 15:58
I solved this by removing the stemmer. which seems a bit unfortunate and I would love a solid alternative.

```js
var index = lunr(function () {
  this.ref('id');
  this.field('content');
});
index.pipeline.remove(lunr.stemmer);
return index;
```

**Comment by olivernn** [comment] 2016-07-09 15:50
Yeah, I think this is a duplicate of #38, closing in favour of #38.

**Closed by olivernn** 2016-07-09 15:50 UTC
